rs_panel_homepage:
    path:     /panel
    defaults: { _controller: RSPanelBundle:Panel:index }

rs_panel_factureform:
    path:     /panel/formulaire-facture
    defaults: { _controller: RSPanelBundle:Panel:factureform }

rs_panel_devisform:
    path:     /panel/formulaire-devis
    defaults: { _controller: RSPanelBundle:Panel:devisform }
            
# Page facture
rs_panel_adminCommande:
     path:      /panel/commandesClients
     defaults: { _controller: RSDestockBundle:Panel:commandes }

