<?php

namespace RS\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    // Cette requête permet de récupérer la liste des membres
    public function getUserProfil()
    {
        // Jointure pour récupérer également les informations de chaques membres
        $query = $this->createQueryBuilder('u')
            ->leftJoin('u.infos', 'i')
            ->addSelect('i')
            ->getQuery()
            ;
        return $query->getResult();
    }
    
    
}

