
rs_core_homepage:
    path:     /
    defaults: { _controller: RSCoreBundle:Core:index }

rs_core_test:
    path:     /test
    defaults: { _controller: RSCoreBundle:Core:test }
    
rs_core_mentionsLegales:
    path:      /mentions_legales
    defaults:  { _controller: RSCoreBundle:Core:mentions_legales }
      
rs_core_menu:
    path:      /menu
    defaults:  { _controller: RSCoreBundle:Core:menu }
       
# Page factures clients
rs_core_facturesClients:
     path:      /panel/facturesClients
     defaults: { _controller: RSCoreBundle:Core:facturesClients }
       
# Page devis clients
rs_core_devisClients:
     path:      /panel/devisClients
     defaults: { _controller: RSCoreBundle:Core:devisClients }    
      
# Page liste des clients
rs_core_listeclients:
     path:      /panel/liste-clients
     defaults: { _controller: RSCoreBundle:Core:listeclients }    
      
# Page mentions legales
rs_core_mentionslegales:
     path:      /mentions-legales
     defaults: { _controller: RSCoreBundle:Core:mentionslegales }    



        
    


        
        
