
rs_core_homepage:
    path:     /
    defaults: { _controller: RSCoreBundle:Core:index }

rs_core_test:
    path:     /test
    defaults: { _controller: RSCoreBundle:Core:test }
    
rs_core_mentionsLegales:
    path:      /mentions_legales
    defaults:  { _controller: RSCoreBundle:Core:mentions_legales }
      
rs_core_menu:
    path:      /menu
    defaults:  { _controller: RSCoreBundle:Core:menu }
       
# Page mentions legales
rs_core_mentionslegales:
     path:      /mentions-legales
     defaults: { _controller: RSCoreBundle:Core:mentionslegales }    



        
    


        
        
