# Page facture
rs_facture_facturePDF:
    path:      /panel/factures/pdf/{id}
    defaults: { _controller: RSFactureBundle:Facture:showFacture }

# Page facture
rs_facture_facture:
    path:      /panel/factures
    defaults: { _controller: RSFactureBundle:Facture:factures }