<?php

namespace RS\PanelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TravauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravauxRepository extends EntityRepository
{
    // Fonction qui permet d'ajouter les articles dans le panier (page panier)
    public function findArray($array)
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t')
            ->where('t.id IN (:array)')
            ->setParameter('array', $array)
            ;
        
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
    
    public function myFindAll()
    {
          return $this
              ->createQueryBuilder('t')
              ->getQuery()
              ->getResult()
              ;
    }
    
}
